version: '3.7' # use, no mínimo, a versão 3.7 para rollback
services:
    redis:
        image: redis:alpine
        networks:
            - frontend
    db:
        image: postgres:10
        volumes:
            - db-data:/var/lib/postgresql/data
        networks:
            - backend
        deploy:
    vote:
        image: mfrancoatdocker/examplevotingapp_vote:curl
        ports:
            - '5000:80'
        networks:
            - frontend
    result:
        image: dockersamples/examplevotingapp_result:before
        ports:
            - '5001:80'
        networks:
            - backend
    worker:
        image: mfrancoatdocker/examplevotingapp_worker:java
        networks:
            - frontend
            - backend
networks:
    frontend:
    backend:
volumes:
    db-data:
