version: '3'
services:
    redis:
        image: redis:alpine
        networks:
            - frontend
    db:
        image: postgres:10
        volumes:
            - db-data:/var/lib/postgresql/data
        networks:
            - backend
    vote:
        image: dockersamples/examplevotingapp_vote:before
        ports:
            - '5000:80'
        networks:
            - frontend
        deploy:
            replicas: 2
            placement:
                constraints:
                    - node.role == worker
    result:
        image: dockersamples/examplevotingapp_result:before
        ports:
            - '5001:80'
        networks:
            - backend
    worker:
        image: mfrancoatdocker/examplevotingapp_worker:java
        networks:
            - frontend
            - backend
        deploy:
            mode: global
            placement:
                constraints:
                    - node.role == worker
networks:
    frontend: null
    backend: null
volumes:
    db-data: null
