# Requisitos:
# ----------
# o serviço db deve:
#   - rodar em um nó com o label ssd=true
# o serviço vote deve:
#   - ter 2 réplicas para garantir alta disponibilidade (HA)
#   - não pode rodar em nós do tipo manager
# o serviço worker deve:
#   - rodar em todos os nós do tipo worker, mesmo quando novos nós
#     forem adicionados ao swarm
#   - rodar uma única tarefa por nó


version: '3'
services:
    redis:
        image: redis:alpine
        networks:
            - frontend
    db:
        image: postgres:10
        volumes:
            - db-data:/var/lib/postgresql/data
        networks:
            - backend
        deploy:
            placement:
                constraints:
                    - node.labels.ssd == true

    vote:
        image: dockersamples/examplevotingapp_vote:before
        ports:
            - '5000:80'
        networks:
            - frontend
        deploy:
            replicas: 2
            placement:
                constraints:
                    - node.role == worker

    result:
        image: dockersamples/examplevotingapp_result:before
        ports:
            - '5001:80'
        networks:
            - backend
    worker:
        image: mfrancoatdocker/examplevotingapp_worker:java
        networks:
            - frontend
            - backend
        deploy:
            mode: global
            placement:
                constraints:
                    - node.role == worker

networks:
    frontend: null
    backend: null
volumes:
    db-data: null
