version: "3.1"

services:
  psql:
    image: postgres
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/psql-pass.txt
      POSTGRES_USER_FILE: /run/secrets/psql-user.txt
    volumes:
      - .:/run/secrets

